name: Auto Update Zee5 Token

on:
  schedule:
    - cron: cron: '45 1 * * *' # Every day at 01:45:52 GMT
  workflow_dispatch:       # Allows manual trigger

jobs:
  update_zee5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Zee5 Update Script
        run: python t5.py
